version: '3.6'
services:
  data:
    image: ubuntu
    volumes: 
      - mysql57-data:/data/mysql57-data
      - mysql80-data:/data/mysql80-data
      - mongodb36-data:/data/mongodb36-data
      - rethinkdb23-data:/data/rethinkdb23-data
      - redis32-data:/data/redis32-data
      - redis40-data:/data/redis40-data

  mysql57:
    image: mysql:5.7
    ports: 
      - "10001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes: 
      - mysql57-data:/var/lib/mysql

  mysql80:
    image: mysql:8.0
    ports: 
      - "10002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes: 
      - mysql80-data:/var/lib/mysql
  
  mongodb36:
    image: mongo:3.6
    ports:
      - "10003:27017"
      - "10004:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb36-data:/data/db
  rethinkdb23:
    image: rethinkdb:2.3
    ports:
      - "10005:8080"
      - "10006:28015"
      - "10007:29015"
    volumes:
      - rethinkdb23-data:/data

  redis32:
    image: redis:3.2
    ports:
      - "10008:6379"
    volumes:
      - redis32-data:/data

  redis40:
    image: redis:4.0
    ports:
      - "10009:6379"
    volumes:
      - redis40-data:/data

  Nginx1.14:
    image: nginx:1.14
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/nginx-conf:/etc/nginx/conf.d"
      - code-sync:/www/code:nocopy
    links:
      - crossbar
      - app
    container_name: nginx

  crossbar:
    image: crossbario/crossbar
    ports:
      - "8080:8080"

  app:
    image: saqing/php-dev:latest
    volumes:
      - code-sync:/www/code:nocopy
    links:
      - mysql57
      - mysql80
      - rethinkdb23
      - mongodb36
      - redis32
      - redis40
      - crossbar
    container_name: app
   
volumes:
  mysql57-data: 
  mysql80-data:
  mongodb36-data:
  rethinkdb23-data:
  redis32-data:
  redis40-data:
  code-sync:
     external: true


