version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - "$PWD/data/redis:/data"
      - "$PWD/conf:/usr/local/etc/redis"
    command: redis-server /usr/local/etc/redis/redis.conf
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - "$PWD/data/mysql:/var/lib/mysql"
      - "$PWD/logs/mysql:/logs"
      - "$PWD/data/mysql:/mysql_data"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  php-fpm:
    image: mileschou/phalcon:7.1-fpm
    volumes:
      - "$PWD/conf/php:/usr/local/etc/php"
      - "$PWD/www:/www"
    links:
      - mysql
      - redis
  nginx-http:
      image: nginx
      volumes:
        - "$PWD/conf/nginx-http:/etc/nginx/conf.d"
        - "$PWD/logs/nginx-http:/wwwlogs"
        - "$PWD/www:/www"
      links:
        - php-fpm
  nginx-proxy:
      image: nginx
      ports:
        - "9999:80"
      volumes:
        - "$PWD/conf/nginx-proxy:/etc/nginx/conf.d"
        - "$PWD/logs/nginx-proxy:/wwwlogs"
      links:
        - nginx-http