version: '2'
services:
  workspace:
    image: saqing/workspace:dev
    volumes:
      - "$PWD/www:/www"
    links:
      - redis
      - mysql
  deepstream:
    image: deepstreamio/deepstream.io
    volumes:
      - "$PWD/conf/deepstream:/etc/deepstream"
    links:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/data/redis:/data"
      - "$PWD/conf/redis:/usr/local/etc/redis"
    command: redis-server --appendonly yes
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "$PWD/data/mysql:/var/lib/mysql"
      - "$PWD/logs/mysql:/logs"
      - "$PWD/data/mysql:/mysql_data"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  php-fpm:
    image: saqing/php-dev
    volumes:
      - "$PWD/conf/php:/usr/local/etc/php"
      - "$PWD/www:/www"
    links:
      - mysql
      - redis
  nginx-http:
    image: nginx
    volumes:
      - "$PWD/conf/nginx-http:/etc/nginx/conf.d"
      - "$PWD/logs/nginx-http:/wwwlogs"
      - "$PWD/www:/www"
    links:
      - php-fpm
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "$PWD/conf/nginx-proxy:/etc/nginx/conf.d"
      - "$PWD/logs/nginx-proxy:/wwwlogs"
    links:
      - nginx-http
      - deepstream
      - workspace
